apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: 214745599154.dkr.ecr.us-east-1.amazonaws.com/order-service:eeec61b9c08b18bc4dd4e2bc368eef358c0b68ba
          ports:
            - containerPort: 3004
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3004"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ORDERS_DB_URL
            - name: AUTH_SERVICE_URL
              value: "http://auth:3002"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3003"

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: ecommerce
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
