apiVersion: v1
kind: Service
metadata:
  name: aiops-assistant
  namespace: aiops
spec:
  selector:
    app: aiops-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
